version: "3"

services:
  app:
    image: siomiz/softethervpn
    cap_add:
      - NET_ADMIN
    environment:
      - SPW=aa123123
      - PSK=vpn
      - USERS=user1:qaz123;user2:qaz123
    ports:
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
      - 1194:1194/udp
      - 5555:5555/tcp
